on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lfs-warning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: LFS Warning
        uses: ppremk/lfs-warning@v3.2
        with:
          filesizelimit: 10MB
